'use client';
/* oxlint-disable next/no-html-link-for-pages, next/no-img-element -- Relative links support static subpath exports; local PNG previews do not use a remote optimizer. */
import { useEffect, useRef, useState } from 'react';
import { MODULES, PRESETS, newProject, validate, parseProject, aboutHTML, readme, siteHTML, themeCSS, noteMistressPack, decodeImages } from '../../packages/neuroforge-core/index.mjs';
import './studio.css';

const STORAGE='neuroforge-studio-v1';
const moduleNames={theme:'Thème',identity:'Identité',languages:'Langues',about:'About',publication:'Page & README'};
const sections=['Application','Identité','Thème','Langues','Livrer'];
const clone=v=>JSON.parse(JSON.stringify(v));
const download=(name,content,type='application/json')=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

export default function ForgeStudio(){
  const [projects,setProjects]=useState([newProject()]);const [selected,setSelected]=useState(0);const [step,setStep]=useState(0);const [locale,setLocale]=useState('fr');const [preview,setPreview]=useState('about');const [message,setMessage]=useState('');const [ready,setReady]=useState(false);const [dirty,setDirty]=useState(false);const [previous,setPrevious]=useState(null);const file=useRef(null);
  const p=projects[selected]||projects[0];const result=validate(p);const enabled=m=>p.modules.includes(m);
  useEffect(()=>{const timer=setTimeout(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){if(raw.length>24000000)throw Error('Sauvegarde trop volumineuse.');const data=JSON.parse(raw);if(!Array.isArray(data)||!data.length||data.length>20)throw Error('Bibliothèque invalide.');data.forEach(v=>parseProject(JSON.stringify(v)));setProjects(data);setLocale(data[0].defaultLocale);}}catch(e){setMessage('Sauvegarde non chargée : '+e.message+' Votre copie stockée est conservée.');}setReady(true);},0);return()=>clearTimeout(timer);},[]);
  if(!ready)return <main className="nf-studio" style={{padding:32}}>Chargement de votre bibliothèque…</main>;
  function update(fn){setProjects(all=>all.map((item,i)=>{if(i!==selected)return item;const next=clone(item);fn(next);return next;}));setDirty(true);setMessage('');}
  const field=(title,value,action,props={})=><label className="nf-field">{title}<input value={value} onChange={e=>action(e.target.value)} {...props}/></label>;
  async function save(){try{if(new Set(projects.map(x=>x.project.id)).size!==projects.length)throw Error('Deux projets portent le même identifiant.');projects.forEach(v=>parseProject(JSON.stringify(v)));for(const v of projects)await decodeImages(v);const old=localStorage.getItem(STORAGE);localStorage.setItem(STORAGE,JSON.stringify(projects));setPrevious(old);setDirty(false);setMessage('Bibliothèque enregistrée sur ce navigateur.');}catch(e){setMessage('Enregistrement refusé : '+e.message);}}
  async function importFile(event){const f=event.target.files?.[0];if(!f)return;try{if(f.size>12000000)throw Error('12 Mo maximum.');const incoming=await decodeImages(parseProject(await f.text()));if(projects.some(x=>x.project.id===incoming.project.id))throw Error('Cet identifiant existe déjà. Changez-le avant import ; aucun projet remplacé.');setProjects(all=>[...all,incoming]);setSelected(projects.length);setLocale(incoming.defaultLocale);setDirty(true);setMessage('Pack importé et validé. Enregistrez pour le conserver.');}catch(e){setMessage('Import refusé : '+e.message);}event.target.value='';}
  async function image(event,kind){const f=event.target.files?.[0];if(!f)return;try{if(f.type!=='image/png'||f.size>4194304)throw Error('PNG uniquement, 4 Mio maximum.');const value=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Lecture impossible.'));r.readAsDataURL(f);});const next=clone(p);next.identity[kind]=value;parseProject(JSON.stringify(next));await decodeImages(next);update(v=>{v.identity[kind]=value;});}catch(e){setMessage('Image refusée : '+e.message);}event.target.value='';}
  async function useNeuroForge(){try{const prefix=window.location.pathname.replace(/\/forge\/?$/,'');const values=await Promise.all(['logo','icon'].map(async kind=>{const response=await fetch(prefix+'/neuroforge/'+kind+'.png');if(!response.ok)throw Error('Ressource NeuroForge indisponible.');const blob=await response.blob();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}));const next=clone(p);next.identity.logo=values[0];next.identity.icon=values[1];await decodeImages(parseProject(JSON.stringify(next)));update(x=>{x.identity=next.identity;});setMessage('Logo et icône NeuroForge chargés depuis les ressources du dépôt.');}catch(e){setMessage(e.message);}}
  async function exportAs(kind){try{await decodeImages(parseProject(JSON.stringify(p)));const id=p.project.id;if(kind==='pack')download(id+'.neuroforge.json',JSON.stringify(p,null,2));if(kind==='about')download(id+'-about-'+locale+'.html',aboutHTML(p,locale),'text/html');if(kind==='site')download('index.html',siteHTML(p,locale),'text/html');if(kind==='readme')download('README.'+locale+'.md',readme(p,locale),'text/markdown');if(kind==='css')download(id+'.css',themeCSS(p),'text/css');if(kind==='native')download('skin.json',JSON.stringify(noteMistressPack(p),null,2));setMessage('Export préparé : '+kind+'. Aucun fichier envoyé à GitHub.');}catch(e){setMessage('Export refusé : '+e.message);}}
  function add(){if(projects.length>=20){setMessage('20 projets maximum dans cette bibliothèque locale.');return;}const id='application-'+Date.now().toString(36);setProjects(all=>[...all,newProject(id)]);setSelected(projects.length);setLocale('fr');setStep(0);setDirty(true);}
  function restore(){if(previous===null)return;try{const data=JSON.parse(previous);data.forEach(x=>parseProject(JSON.stringify(x)));localStorage.setItem(STORAGE,previous);setProjects(data);setSelected(0);setLocale(data[0].defaultLocale);setPrevious(null);setDirty(false);setMessage('Sauvegarde précédente restaurée.');}catch(e){setMessage(e.message);}}
  let html='';if(!result.errors.length){try{html=preview==='site'?siteHTML(p,locale):aboutHTML(p,locale);}catch{html='';}}
  return <main className="nf-studio">
    <header className="nf-header"><a href="../" className="nf-home" title="Atelier de marque existant">N<span>NEURO FORGE<small>Atelier commun · premier lot local</small></span></a><div><span className="nf-save-state">{dirty?'Modifications non enregistrées':'Bibliothèque locale'}</span><button onClick={save} disabled={!ready}>Enregistrer</button></div></header>
    <div className="nf-workflow"><span>01 Configurer</span><span>02 Prévisualiser</span><span>03 Vérifier</span><span>04 Exporter</span></div>
    <div className="nf-grid">
      <aside className="nf-projects"><p className="nf-eyebrow">APPLICATIONS</p>{projects.map((x,i)=><button key={i} className={i===selected?'selected':''} onClick={()=>{setSelected(i);setLocale(x.defaultLocale);setMessage('');}}><strong>{x.project.name||'Sans nom'}</strong><small>{x.project.id}</small></button>)}<button onClick={add}>+ Nouvelle application</button><button onClick={()=>file.current?.click()}>Importer un pack</button><input ref={file} type="file" accept="application/json,.json" onChange={importFile} hidden/><div className="nf-side-note">Les projets sont enregistrés dans ce navigateur. Exportez un pack pour le transporter ou le sauvegarder ailleurs.</div><a href="../">Ouvrir l’atelier de marque existant ↗</a></aside>
      <section className="nf-editor" aria-label="Configuration NeuroForge"><div className="nf-title"><p className="nf-eyebrow">CONFIGURATION PAR APPLICATION</p><h1>{p.project.name}</h1><p>Une identité, des langues et des exports cohérents.</p></div>
        <nav className="nf-tabs" aria-label="Étapes">{sections.map((s,i)=><button key={s} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{s}</button>)}</nav>
        {step===0&&<><h2>Application</h2><div className="nf-fields">{field('Nom',p.project.name,v=>update(x=>{x.project.name=v;}))}{field('Identifiant stable',p.project.id,v=>update(x=>{x.project.id=v;}))}{field('Version application',p.project.version,v=>update(x=>{x.project.version=v;}))}{field('Version du pack',p.packVersion,v=>update(x=>{x.packVersion=v;}))}{field('Dépôt GitHub',p.project.repository,v=>update(x=>{x.project.repository=v;}),{placeholder:'https://github.com/propriétaire/projet'})}{field('Licence',p.project.license,v=>update(x=>{x.project.license=v;}),{placeholder:'À vérifier dans le dépôt'})}</div><h2>Modules</h2><div className="nf-modules">{MODULES.map(m=><label key={m}><input type="checkbox" checked={enabled(m)} onChange={()=>update(x=>{x.modules=enabled(m)?x.modules.filter(k=>k!==m):[...x.modules,m];})}/><span>{moduleNames[m]}</span></label>)}</div><p className="nf-hint">Désactiver un module conserve ses réglages mais retire son effet des exports. La version et la licence doivent correspondre à votre application.</p></>}
        {step===1&&<><h2>Identité NeuroForge</h2><button onClick={useNeuroForge}>Utiliser les ressources NeuroForge</button><p>Logo pour l’About, icône pour le futur raccordement des applications. PNG, 4 Mio maximum.</p>{!enabled('identity')&&<p className="nf-notice">Module désactivé : identité conservée, non appliquée aux exports.</p>}<div className="nf-assets">{['logo','icon'].map(k=><div key={k}>{p.identity[k]?<img src={p.identity[k]} alt={k==='logo'?'Logo du projet':'Icône du projet'}/>:<div className="nf-asset-empty">{k==='logo'?'Logo':'Icône'}</div>}<label className="nf-upload">Importer {k==='logo'?'le logo':'l’icône'}<input type="file" accept="image/png" onChange={e=>image(e,k)}/></label><button onClick={()=>update(x=>{x.identity[k]='';})} disabled={!p.identity[k]}>Retirer</button></div>)}</div>{field('Signature',p.identity.signature,v=>update(x=>{x.identity.signature=v;}))}<p className="nf-hint">L’icône est transportée dans le pack. Elle ne remplace pas encore l’icône du bundle macOS. Aucune icône interne de bouton n’est remplacée.</p></>}
        {step===2&&<><h2>Thème visuel</h2><div className="nf-presets">{Object.entries(PRESETS).map(([id,t])=><button key={id} onClick={()=>update(x=>{x.theme={...t,typography:x.theme.typography,density:x.theme.density};})}><i style={{background:t.background,borderColor:t.accent}}/>{t.name}</button>)}</div><div className="nf-fields">{['background','surface','text','muted','accent'].map(k=><label className="nf-field" key={k}>{{background:'Fond',surface:'Surface',text:'Texte',muted:'Texte secondaire',accent:'Accent'}[k]}<div className="nf-color"><input type="color" aria-label={'Couleur '+k} value={p.theme[k]} onChange={e=>update(x=>{x.theme[k]=e.target.value;})}/><input aria-label={'Valeur '+k} value={p.theme[k]} onChange={e=>update(x=>{x.theme[k]=e.target.value;})}/></div></label>)}<label className="nf-field">Apparence<select value={p.theme.appearance} onChange={e=>update(x=>{x.theme.appearance=e.target.value;})}><option value="dark">Sombre</option><option value="light">Claire</option></select></label><label className="nf-field">Police<select value={p.theme.typography.family} onChange={e=>update(x=>{x.theme.typography.family=e.target.value;})}><option value="system">Système</option><option value="monospace">Monospace</option></select></label>{field('Taille de base',p.theme.typography.size,v=>update(x=>{x.theme.typography.size=Number(v);}),{type:'number',min:11,max:18})}<label className="nf-field">Densité<select value={p.theme.density} onChange={e=>update(x=>{x.theme.density=e.target.value;})}><option value="comfortable">Confortable</option><option value="compact">Compacte</option></select></label></div><p className="nf-hint">Les couleurs métier, les données et la disposition des panneaux restent propres à chaque application.</p></>}
        {step===3&&<><h2>Langues & textes</h2><div className="nf-fields"><label className="nf-field">Langue de repli<select value={p.defaultLocale} onChange={e=>update(x=>{x.defaultLocale=e.target.value;})}>{p.locales.map(l=><option key={l}>{l}</option>)}</select></label><label className="nf-field">Langue à éditer<select value={locale} onChange={e=>setLocale(e.target.value)}>{p.locales.map(l=><option key={l}>{l}</option>)}</select></label></div>{['description','purpose','audience','limits'].map(k=><label className="nf-field" key={k}>{{description:'Description courte',purpose:'À quoi sert cette application ?',audience:'Pour qui ?',limits:'Limites connues'}[k]}<textarea rows={3} value={p.translations[locale]?.[k]||''} onChange={e=>update(x=>{x.translations[locale][k]=e.target.value;})}/></label>)}<p className="nf-hint">FR et EN pour ce premier lot. Un texte absent reprend la langue de repli. Les textes internes des applications ne sont pas encore traduits par ce module.</p></>}
        {step===4&&<><h2>Vérifier & livrer</h2><p>Les exports sont locaux. Aucune publication ni modification de dépôt n’est automatique.</p><div className="nf-export-grid"><button onClick={()=>exportAs('pack')}>Exporter le pack commun</button><button disabled={!enabled('about')} onClick={()=>exportAs('about')}>Exporter About HTML</button><button disabled={!enabled('publication')} onClick={()=>exportAs('readme')}>Exporter README</button><button disabled={!enabled('publication')} onClick={()=>exportAs('site')}>Exporter page GitHub</button><button disabled={!enabled('theme')} onClick={()=>exportAs('css')}>Exporter CSS</button><button disabled={!enabled('theme')} onClick={()=>exportAs('native')}>Exporter skin NoteMistress</button></div><p className="nf-notice">NoteMistress : export de compatibilité du thème seulement, sans identité ni About. L’application native doit être raccordée et vérifiée séparément.</p><button disabled={previous===null} onClick={restore}>Restaurer la sauvegarde précédente</button><p className="nf-hint">Restauration de la bibliothèque entière, disponible après un nouvel enregistrement dans cette session.</p></>}
        <div className="nf-validation" aria-live="polite"><strong>{result.errors.length?result.errors.length+' erreur(s) à corriger':'Structure valide'}</strong>{result.errors.map(s=><p key={s} className="nf-error">{s}</p>)}<details><summary>{result.warnings.length} texte(s) manquant(s)</summary>{result.warnings.map(s=><p key={s}>{s}</p>)}</details></div><output className="nf-status">{message}</output>
      </section>
      <aside className="nf-preview"><p className="nf-eyebrow">APERÇU DE L’EXPORT</p><div className="nf-preview-controls"><select aria-label="Type d’aperçu" value={preview} onChange={e=>setPreview(e.target.value)}><option value="about">About</option><option value="site">Page publique</option></select><select aria-label="Langue de l’aperçu" value={locale} onChange={e=>setLocale(e.target.value)}>{p.locales.map(l=><option key={l}>{l}</option>)}</select></div>{html?<iframe title="Aperçu de l’export" sandbox="" srcDoc={html}/>:<div className="nf-preview-empty">{result.errors.length?'Corrigez les erreurs pour prévisualiser.':preview==='site'?'Complétez le dépôt, la licence et les textes de repli pour préparer la page publique.':'Activez le module About pour prévisualiser.'}</div>}<p className="nf-hint">Rendu du fichier exporté. Ce panneau ne prouve pas l’intégration dans une application.</p><div className="nf-compat"><strong>Raccordements</strong><p>Web : pack structuré + adaptateur</p><p>NoteMistress : thème v1 seulement</p><p>GitHub : fichiers à publier après revue</p></div></aside>
    </div>
  </main>;
}
