'use client';
import {useState} from 'react';
import UXPreview from './ux-preview.jsx';
import {REFERENCES,UX_BLOCKS} from '../packages/neuroforge-core/ux-blocks.mjs';
export default function UXWorkshop({project,onChange,onApply,onSession,embedded=false}){
 const [search,setSearch]=useState('');const [revision,setRevision]=useState(0);
 const integration=project.integration||{},blocks=integration.blocks||[],references=integration.references||[];

 const update=(next)=>onChange({...integration,...next});
 function toggleBlock(id){let next=blocks.includes(id)?blocks.filter(x=>x!==id):[...blocks,id];if(id==='library'&&!next.includes(id))next=next.filter(x=>!['tree','compare','inspector'].includes(x));if(['tree','compare','inspector'].includes(id)&&next.includes(id)&&!next.includes('library'))next.push('library');update({blocks:next,references:references.length?references:REFERENCES.map(r=>r.id)});}
 return <section className={embedded?'ux-workshop embedded':'ux-workshop'}><div className="ux-controls"><div className="panel-title"><h2>Blocs à combiner</h2><span>{blocks.length} / 8</span></div><p>Interactions locales, réutilisables en HTML. Les services cités restent à raccorder.</p><div className="ux-actions"><button disabled={!blocks.length} onClick={onApply}>Appliquer à mon aperçu</button><button onClick={()=>update({blocks:UX_BLOCKS.map(b=>b.id),references:REFERENCES.map(r=>r.id)})}>Tout inclure · 8 blocs + 27 références</button><button onClick={()=>update({blocks:[],references:[]})}>Vider la sélection</button></div><div className="ux-block-grid">{UX_BLOCKS.map(b=><label key={b.id} aria-label={b.name} className={'ux-block '+(blocks.includes(b.id)?'selected':'')}><input type="checkbox" checked={blocks.includes(b.id)} onChange={()=>toggleBlock(b.id)}/><span><strong>{b.name}</strong><small>{b.detail}</small></span></label>)}</div><details className="ux-references"><summary>27 références · {references.length} incluses au kit</summary><label>Filtrer les références<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, catégorie…"/></label>{REFERENCES.filter(r=>(r.name+' '+r.category).toLowerCase().includes(search.toLowerCase())).map(r=><article key={r.id}><label><input type="checkbox" checked={references.includes(r.id)} onChange={()=>update({references:references.includes(r.id)?references.filter(id=>id!==r.id):[...references,r.id]})}/><strong>{r.name}</strong></label><small>{r.category} · {r.status}</small><p>{r.idea}</p><a href={r.url} target="_blank" rel="noreferrer">Voir la source ↗</a>{r.km&&<small>Fiche déjà référencée dans votre liste</small>}</article>)}</details><p>« Enregistrer » conserve cette sélection. Le kit inclut le code de l’aperçu, les choix et la provenance. Les notes de démonstration s’exportent dans l’aperçu.</p></div>{!embedded&&<div id="live-preview" className="ux-live"><div className="panel-title"><div><small>VOTRE COMPOSITION · {project.theme.name}</small><h2>Aperçu interactif</h2></div><button onClick={()=>setRevision(v=>v+1)}>Relancer l’aperçu</button></div><UXPreview key={revision} title="Composition des blocs UX" project={project} onSession={onSession}/><p>La skin et l’identité du projet s’appliquent à cette composition. Les interactions utilisent les références ; elles n’accèdent pas à vos fichiers.</p></div>}</section>;
}
