export const COMPOSITIONS=[
 {id:'cockpit',name:'Cockpit Glass',skin:'codepen-yzlbvop',description:'Navigation latérale, bibliothèque centrale et inspecteur à droite.',areas:'"tree library inspector" "tree compare inspector" "timeline timeline timeline" "sources sources sources"',columns:'170px minmax(0,1fr) 220px',style:'glass'},
 {id:'library',name:'Bibliothèque éditoriale',skin:'codepen-oppygky',description:'Grand catalogue, filtres en tête et comparaison sous la grille.',areas:'"tree tree" "library library" "compare inspector" "sources timeline"',columns:'minmax(0,2fr) minmax(0,1fr)',style:'brutal'},
 {id:'desktop',name:'Bureau rétro',skin:'codepen-mwgjppa',description:'Panneaux en fenêtres, barres de titre et navigation compacte.',areas:'"library inspector" "tree compare" "timeline sources"',columns:'minmax(0,3fr) minmax(0,2fr)',style:'retro'},
 {id:'studio',name:'Studio créatif',skin:'codepen-yzgopoq',description:'Inspecteur à gauche, catalogue à droite et séquence en bas.',areas:'"inspector library" "tree library" "timeline timeline" "compare sources"',columns:'220px minmax(0,1fr)',style:'soft'},
 {id:'terminal',name:'Terminal de commande',skin:'codepen-wmggwz',description:'Index dense, commandes en tête et panneaux de diagnostic.',areas:'"tree library" "inspector library" "compare timeline" "sources sources"',columns:'220px minmax(0,1fr)',style:'neon'},
 {id:'reading',name:'Lecture minimale',skin:'codepen-pjbzpq',description:'Colonne de lecture, repères discrets et fiches en liste.',areas:'"tree" "library" "inspector" "compare" "timeline" "sources"',columns:'minmax(0,1fr)',style:'minimal'},
];
export function compositionFor(project){return COMPOSITIONS.find(c=>c.id===project.integration?.composition)||COMPOSITIONS[0];}
export function compositionCSS(c){
 return `main{grid-template-columns:${c.columns};grid-template-areas:${c.areas};align-items:start}#section-tree{grid-area:tree}#section-library{grid-area:library}#section-inspector{grid-area:inspector}#section-compare{grid-area:compare}#section-timeline{grid-area:timeline}#section-sources{grid-area:sources}main>section{max-height:660px;overflow:auto}#section-tree #tree{display:grid;gap:4px}#tree details button{display:block;width:100%;margin:5px 0;text-align:left}body[data-composition=library] h1{font-size:40px;letter-spacing:-2px}body[data-composition=library] #section-tree #tree{display:flex}body[data-composition=desktop] section>h2{background:var(--nf-accent);color:white;padding:8px;margin:-18px -18px 14px;font-size:13px}body[data-composition=desktop] section{border-radius:0}body[data-composition=studio] #section-timeline{min-height:200px}body[data-composition=terminal]{font-family:ui-monospace,monospace}body[data-composition=terminal] section{padding:12px}body[data-composition=terminal] #items{grid-template-columns:1fr}body[data-composition=terminal] #items article{padding:4px;border-width:0 0 1px}body[data-composition=reading] main{max-width:860px;margin:auto}body[data-composition=reading] #items{grid-template-columns:1fr}body[data-composition=reading] #tree{display:flex}body[data-composition=reading] section{border-width:0 0 1px;border-radius:0}body[data-composition=reading] .item-select{text-align:left;padding:16px}@media(max-width:780px){main{grid-template-columns:minmax(0,1fr);grid-template-areas:'tree' 'library' 'inspector' 'compare' 'timeline' 'sources'}main>section{max-height:none}#section-tree #tree{display:flex}#section-library{max-height:650px}h1{overflow-wrap:anywhere}}`;
}
export function validSession(s){
 if(!s||typeof s!=='object'||Array.isArray(s)||Object.keys(s).some(k=>!['selected','compare','favorites','notes','clips','query','category','favOnly','list','position'].includes(k)))return false;
 const ids=a=>Array.isArray(a)&&a.length<=27&&a.every(v=>/^ref-\d{2}$/.test(v))&&new Set(a).size===a.length;
 return typeof s.selected==='string'&&s.selected.length<32&&ids(s.compare)&&s.compare.length<=4&&ids(s.favorites)&&s.notes&&typeof s.notes==='object'&&!Array.isArray(s.notes)&&Object.keys(s.notes).length<=27&&Object.entries(s.notes).every(([k,v])=>/^ref-\d{2}$/.test(k)&&typeof v==='string'&&v.length<=8000)&&Array.isArray(s.clips)&&s.clips.length<=100&&s.clips.every(c=>c&&Object.keys(c).every(k=>['name','duration'].includes(k))&&typeof c.name==='string'&&c.name.length<=80&&[5,10,30].includes(c.duration))&&typeof s.query==='string'&&s.query.length<=200&&typeof s.category==='string'&&s.category.length<=100&&typeof s.favOnly==='boolean'&&typeof s.list==='boolean'&&Number.isFinite(s.position)&&s.position>=0&&s.position<=3000;
}
