import {uxHTML,REFERENCES,UX_BLOCKS} from './ux-blocks.mjs';
import {assertProject} from './index.mjs';
export function unifiedHTML(source,project){
 assertProject(project);
 if(!source.includes('nyx-unified-runtime'))throw Error('Base Nyx intégré unifiée absente.');
 const data=JSON.stringify({project,blockHTML:uxHTML({...project,integration:{...project.integration,blocks:UX_BLOCKS.map(b=>b.id)}}),references:REFERENCES.filter(r=>project.integration?.references?.includes(r.id)),skins:[{id:'selected',name:project.theme.name}]}).replace(/</g,'\\u003c');
 return source.replace('<head>','<head><script>window.__NYX_INITIAL='+data+';</script>');
}
export function unifiedRuntime(){
 let current=null, options=[],mounted=false,blockRoot=null;
 if(window.parent!==window)document.body.dataset.nyxEmbedded="true";
 const store={};
 try{Object.assign(store,JSON.parse(localStorage.getItem('nyx-unified-workspace-v1')||'{}'));}catch{}
 const emit=()=>{try{localStorage.setItem('nyx-unified-workspace-v1',JSON.stringify(store));}catch{}if(window.parent!==window)window.parent.postMessage({type:'nyx-native-state',state:{...store}},window.origin);};
 window.NyxStore={getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v);emit();},removeItem:k=>{delete store[k];emit();}};
 if(window.__NYX_INITIAL?.project?.integration?.nativeState)Object.assign(store,window.__NYX_INITIAL.project.integration.nativeState);
 const style=document.createElement('style');style.id='nyx-shared-theme';
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function css(t){return `*{--ink-0:${t.background}!important;--ink-1:${t.surface}!important;--ink-2:${t.surface}!important;--ink-3:${t.surface}!important;--ink-4:color-mix(in srgb,${t.text} 22%,${t.surface})!important;--bone-0:${t.text}!important;--bone-1:${t.text}!important;--bone-2:${t.muted}!important;--bone-3:${t.muted}!important;--sel-blue:${t.accent}!important;--bg:${t.background}!important;--panel:${t.surface}!important;--ink:${t.text}!important;--muted:${t.muted}!important;--accent:${t.accent}!important;--soft:${t.surface}!important;--line:color-mix(in srgb,${t.text} 22%,${t.surface})!important}[hidden]{display:none!important}body{background:${t.background};color:${t.text}}#dc-root>div{height:calc(100vh - 46px)!important}body[data-nyx-embedded] #dc-root>div{height:100vh!important}body[data-nyx-embedded] #nyx-shared-settings{display:none!important}#nd button{box-shadow:none!important;border-radius:5px!important}#nd .head{font-size:11px}.nyx-annotation-panel{display:none!important}#nd,#nd .bar,#nd .pane,#nd .head,#nd .tabs,#nd .properties,#nd footer,#nd textarea,#nd input,#nd button,#nd select,.card,.item,input,textarea,select{background:${t.surface}!important;color:${t.text}!important;border-color:color-mix(in srgb,${t.text} 22%,${t.surface})!important}#nd .workspace,#nd aside,#nd .content,.right{background:${t.background}!important;color:${t.text}!important}#nd .muted,#nd .empty,#nd .tools{color:${t.muted}!important}#nyx-shared-settings{display:flex;gap:8px;align-items:center;padding:8px 12px;background:${t.surface};color:${t.text};border-bottom:1px solid ${t.muted};font:12px system-ui}#nyx-shared-settings img{width:24px;height:24px;object-fit:contain}#nyx-shared-settings select{max-width:180px}@media(max-width:700px){#nyx-shared-settings>span{display:none}#nyx-shared-settings strong{white-space:nowrap}}#nyx-block-root{height:100%;overflow:auto;background:${t.background};color:${t.text};font:13px system-ui;padding:12px}#nyx-block-root main{display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr))}#nyx-block-root section{padding:14px;border:1px solid ${t.muted};border-radius:${t.visual?.radius||6}px;background:${t.surface}}#nyx-block-root button,#nyx-block-root input,#nyx-block-root textarea,#nyx-block-root select{font:inherit;color:inherit;background:${t.surface};border:1px solid ${t.muted};padding:7px;border-radius:4px;max-width:100%}#nyx-block-root #items{display:grid;gap:8px}#nyx-block-root article{padding:10px;border:1px solid ${t.muted}}#nyx-block-root .row{display:flex;gap:8px;flex-wrap:wrap}#nyx-block-root button{cursor:pointer}#nyx-block-root button[aria-pressed=true]{outline:2px solid ${t.accent}}#nyx-block-root .item-select{text-align:left;width:100%}#nyx-block-root textarea{width:100%}#nyx-block-root #tree{display:flex;gap:8px;flex-wrap:wrap}#nyx-block-root #clips{display:flex;gap:8px;flex-wrap:wrap}#nyx-block-root dialog{background:${t.surface};color:${t.text}}`};
 function apply(data){
  if(!data?.project?.theme)return;
  const t=data.project.theme;if(!['background','surface','text','muted','accent'].every(k=>/^#[\da-f]{6}$/i.test(t[k])))return;
  current=data.project;options=data.skins||options;style.textContent=css(t);if(!style.isConnected)document.head.append(style);
  const settings=document.getElementById('nyx-shared-settings');if(settings){settings.querySelector('strong').textContent=current.project.name;const select=settings.querySelector('select');select.innerHTML=options.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>').join('');const match=options.find(s=>s.name===t.name);if(match)select.value=match.id;settings.querySelector('[data-logo]').src=current.identity.logo||'';settings.querySelector('[data-logo]').hidden=!current.identity.logo;settings.querySelector('[data-icon]').src=current.identity.icon||'';settings.querySelector('[data-icon]').hidden=!current.identity.icon;}
  const registry=document.querySelector('iframe[data-nyx-registry]');if(registry?.contentDocument?.head){let s=registry.contentDocument.getElementById('shared-nyx-theme');if(!s){s=registry.contentDocument.createElement('style');s.id='shared-nyx-theme';registry.contentDocument.head.append(s);}s.textContent=css(t);const signature=current.project.name+'|'+t.name;if(registry.dataset.identity!==signature){registry.dataset.identity=signature;registry.contentWindow.applyNyxProject?.(current,options);}}
  if(data.blockHTML&&!mounted){const parsed=new DOMParser().parseFromString(data.blockHTML,'text/html');const root=document.createElement('div');blockRoot=root;root.id='nyx-block-root';root.innerHTML='<header><h2>Bibliothèque & outils</h2><p>Blocs locaux · références documentaires, services non connectés</p></header>';for(const node of parsed.querySelectorAll('main,dialog,output'))root.append(node);document.body.append(root);mounted=true;window.__NYX_MOUNT_BLOCKS({id:current.project.id,blocks:current.integration?.blocks||[],references:data.references||[],state:current.integration?.session||null});}
  if(mounted){if(data.references)window.__NYX_UPDATE_BLOCKS?.({references:data.references,blocks:current.integration?.blocks||[]});const allowed=new Set(current.integration?.blocks||[]);document.querySelectorAll('#nyx-block-root section[id^="section-"]').forEach(el=>el.hidden=!allowed.has(el.id.replace('section-','')));}
 }
 window.NyxSelectThemeName=name=>{const match=options.find(s=>s.name===name);if(match&&window.parent!==window)window.parent.postMessage({type:'nyx-theme-select',id:match.id},window.origin);};
 window.NyxUnifiedApply=apply;
 window.addEventListener('message',e=>{if(e.source!==window.parent||e.origin!==window.origin)return;if(e.data?.type==='nyx-project')apply(e.data);});
 function renderLocalIcons(){for(const el of document.querySelectorAll('i[data-lucide]')){const name=el.getAttribute('data-lucide'),nodes=window.__NYX_ICON_NODES?.[name];if(!nodes||el.dataset.rendered===name)continue;el.dataset.rendered=name;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');for(const [k,v] of Object.entries({viewBox:'0 0 24 24',width:'100%',height:'100%',fill:'none',stroke:'currentColor','stroke-width':'1.7','stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true'}))svg.setAttribute(k,v);for(const [tag,attrs] of nodes){const n=document.createElementNS(svg.namespaceURI,tag);for(const [k,v] of Object.entries(attrs))if(k!=='key')n.setAttribute(k,v);svg.append(n);}el.replaceChildren(svg);}}
 const observer=new MutationObserver(()=>{
  renderLocalIcons();
  const shell=window.NyxShell;if(!shell)return;
  let settings=document.getElementById('nyx-shared-settings');
  if(!settings){settings=document.createElement('div');settings.id='nyx-shared-settings';settings.innerHTML='<img data-logo alt="Logo"><img data-icon alt="Icône"><strong>Nyx intégré</strong><label> Thème <select aria-label="Thème de Nyx intégré"></select></label><span>Dashboard · Documents · Registry · Bibliothèque</span>';const host=document.getElementById('dc-root');host?.before(settings);settings.querySelector('select').onchange=e=>{if(window.parent!==window)window.parent.postMessage({type:'nyx-theme-select',id:e.target.value},window.origin);};if(current)apply({project:current});}
  const root=blockRoot,slot=document.getElementById('nyx-blocks-slot');if(root){if(slot&&root.parentNode!==slot)slot.append(root);if(!slot&&root.parentNode!==document.body)document.body.append(root);root.hidden=!slot;}
  const r=document.querySelector('iframe[data-nyx-registry]');if(r&&!r.dataset.shared){r.dataset.shared='true';r.addEventListener('load',()=>{if(current)apply({project:current});});}
 });observer.observe(document.body,{childList:true,subtree:true});
 if(window.parent!==window)window.parent.postMessage({type:'nyx-unified-ready'},window.origin==='null'?'*':window.origin);
 if(window.__NYX_INITIAL)apply(window.__NYX_INITIAL);
}
